package javaweb;

import org.oorsprong.websamples.TCountryInfo;
import org.oorsprong.websamples_countryinfo.CountryInfoService;

public class Del_C_VG2 {

	/**
	 * Use the autogenerated classes from apache cfx maven plugin to get the data
	 * from the server
	 * 
	 * @param args
	 */
	public static void main(String[] args) {
		CountryInfoService cs = new CountryInfoService();
		String[] arr = new String[] { "SE", "US", "JP", "HU", "AM", "IS", "CH", "CA" };

		for (String string : arr) {
			TCountryInfo fc = cs.getCountryInfoServiceSoap().fullCountryInfo(string);

			System.out.println("Country: " + fc.getSName());
			System.out.println("Capital: " + fc.getSCapitalCity());
			System.out.println("Currency: " + fc.getSCurrencyISOCode());
			fc.getLanguages().getTLanguage().forEach(s -> System.out.println("Langues: " + s.getSName()));
			System.out.println();
		}
	}

}
